/**
 * Mock bookings data for Sage & Stone Wellness.
 * MOCK DATA - Replace with real booking API when backend is ready.
 */

export const MOCK_BOOKINGS = [
  {
    id: 'bk-001',
    clientName: 'Catherine M.',
    clientEmail: 'catherine.m@email.com',
    clientPhone: '(713) 555-0201',
    serviceId: 'deep-tissue-massage',
    serviceName: 'Deep Tissue Massage',
    providerId: 'staff-001',
    providerName: 'Elena Vasquez',
    date: '2026-03-25',
    time: '10:00 AM',
    status: 'confirmed',
    notes: 'Focus on lower back and shoulders. Prefers firm pressure.',
    createdAt: '2026-03-20T14:30:00Z',
  },
  {
    id: 'bk-002',
    clientName: 'Priya S.',
    clientEmail: 'priya.s@email.com',
    clientPhone: '(713) 555-0202',
    serviceId: 'signature-facial',
    serviceName: 'Signature Facial',
    providerId: 'staff-002',
    providerName: 'Grace Kim',
    date: '2026-03-25',
    time: '11:00 AM',
    status: 'confirmed',
    notes: 'Sensitive skin. Has rosacea on cheeks.',
    createdAt: '2026-03-19T09:15:00Z',
  },
  {
    id: 'bk-003',
    clientName: 'Lauren T.',
    clientEmail: 'lauren.t@email.com',
    clientPhone: '(713) 555-0203',
    serviceId: 'botox-dysport',
    serviceName: 'Botox & Dysport',
    providerId: 'staff-003',
    providerName: 'Dr. Amara Okafor',
    date: '2026-03-25',
    time: '2:00 PM',
    status: 'pending',
    notes: 'First time patient. Consultation completed 3/18.',
    createdAt: '2026-03-21T16:45:00Z',
  },
  {
    id: 'bk-004',
    clientName: 'David & Maria K.',
    clientEmail: 'david.k@email.com',
    clientPhone: '(713) 555-0204',
    serviceId: 'couples-massage',
    serviceName: 'Couples Massage',
    providerId: 'staff-001',
    providerName: 'Elena Vasquez & Maya Chen',
    date: '2026-03-24',
    time: '3:00 PM',
    status: 'completed',
    notes: 'Anniversary celebration. Requested champagne add-on.',
    createdAt: '2026-03-18T11:20:00Z',
  },
  {
    id: 'bk-005',
    clientName: 'Daniela R.',
    clientEmail: 'daniela.r@email.com',
    clientPhone: '(713) 555-0205',
    serviceId: 'head-spa-ritual',
    serviceName: 'Head Spa Ritual',
    providerId: 'staff-004',
    providerName: 'Maya Chen',
    date: '2026-03-26',
    time: '9:00 AM',
    status: 'confirmed',
    notes: 'Repeat client. Loves the scalp treatment.',
    createdAt: '2026-03-22T08:00:00Z',
  },
  {
    id: 'bk-006',
    clientName: 'Sophia L.',
    clientEmail: 'sophia.l@email.com',
    clientPhone: '(713) 555-0206',
    serviceId: 'microneedling',
    serviceName: 'Microneedling',
    providerId: 'staff-002',
    providerName: 'Grace Kim',
    date: '2026-03-26',
    time: '1:00 PM',
    status: 'pending',
    notes: 'Second session in series of 4. Acne scarring treatment.',
    createdAt: '2026-03-23T10:30:00Z',
  },
  {
    id: 'bk-007',
    clientName: 'Amanda F.',
    clientEmail: 'amanda.f@email.com',
    clientPhone: '(713) 555-0207',
    serviceId: 'chemical-peel',
    serviceName: 'Chemical Peel',
    providerId: 'staff-002',
    providerName: 'Grace Kim',
    date: '2026-03-23',
    time: '4:00 PM',
    status: 'completed',
    notes: 'Medium-depth peel. Provided aftercare kit.',
    createdAt: '2026-03-17T13:15:00Z',
  },
  {
    id: 'bk-008',
    clientName: 'Michael B.',
    clientEmail: 'michael.b@email.com',
    clientPhone: '(713) 555-0208',
    serviceId: 'swedish-massage',
    serviceName: 'Swedish Massage',
    providerId: 'staff-001',
    providerName: 'Elena Vasquez',
    date: '2026-03-22',
    time: '5:00 PM',
    status: 'cancelled',
    notes: 'Client called to cancel - work conflict.',
    createdAt: '2026-03-16T15:40:00Z',
  },
  {
    id: 'bk-009',
    clientName: 'Jessica W.',
    clientEmail: 'jessica.w@email.com',
    clientPhone: '(713) 555-0209',
    serviceId: 'anti-aging-facial',
    serviceName: 'Anti-Aging Facial',
    providerId: 'staff-002',
    providerName: 'Grace Kim',
    date: '2026-03-27',
    time: '10:00 AM',
    status: 'pending',
    notes: 'New client referral from Lauren T.',
    createdAt: '2026-03-24T07:50:00Z',
  },
  {
    id: 'bk-010',
    clientName: 'Rachel N.',
    clientEmail: 'rachel.n@email.com',
    clientPhone: '(713) 555-0210',
    serviceId: 'relaxation-package',
    serviceName: 'Relaxation Package',
    providerId: 'staff-001',
    providerName: 'Elena Vasquez',
    date: '2026-03-28',
    time: '9:00 AM',
    status: 'confirmed',
    notes: 'Birthday gift from spouse. Full half-day package.',
    createdAt: '2026-03-23T14:20:00Z',
  },
  {
    id: 'bk-011',
    clientName: 'Thomas G.',
    clientEmail: 'thomas.g@email.com',
    clientPhone: '(713) 555-0211',
    serviceId: 'deep-tissue-massage',
    serviceName: 'Deep Tissue Massage',
    providerId: 'staff-004',
    providerName: 'Maya Chen',
    date: '2026-03-21',
    time: '2:00 PM',
    status: 'completed',
    notes: 'Athletic client. Post-marathon recovery session.',
    createdAt: '2026-03-15T09:30:00Z',
  },
  {
    id: 'bk-012',
    clientName: 'Emily C.',
    clientEmail: 'emily.c@email.com',
    clientPhone: '(713) 555-0212',
    serviceId: 'korean-body-scrub',
    serviceName: 'Korean Body Scrub',
    providerId: 'staff-004',
    providerName: 'Maya Chen',
    date: '2026-03-27',
    time: '3:00 PM',
    status: 'confirmed',
    notes: 'First time trying body scrub. Explained process during consultation call.',
    createdAt: '2026-03-24T11:00:00Z',
  },
];
