/**
 * Mock leads/inquiries data for Sage & Stone Wellness.
 * MOCK DATA - Replace with real CRM/lead API when backend is ready.
 */

export const MOCK_LEADS = [
  {
    id: 'lead-001',
    name: 'James R.',
    email: 'james.r@email.com',
    phone: '(713) 555-0301',
    serviceInterest: 'Botox & Dysport',
    message: 'I am interested in learning more about Botox for forehead lines. I have never had injectables before and would like to schedule a consultation.',
    status: 'new',
    createdAt: '2026-03-24T09:15:00Z',
  },
  {
    id: 'lead-002',
    name: 'Amanda F.',
    email: 'amanda.f@email.com',
    phone: '(713) 555-0302',
    serviceInterest: 'Microneedling',
    message: 'I have acne scarring on my cheeks and chin. Would microneedling be a good option for me? I would love to discuss during a consultation.',
    status: 'contacted',
    createdAt: '2026-03-22T14:30:00Z',
  },
  {
    id: 'lead-003',
    name: 'Robert H.',
    email: 'robert.h@email.com',
    phone: '(713) 555-0303',
    serviceInterest: 'Body Contouring',
    message: 'Looking for non-surgical options for my midsection. I exercise regularly but cannot seem to lose the stubborn area. What do you recommend?',
    status: 'new',
    createdAt: '2026-03-23T16:45:00Z',
  },
  {
    id: 'lead-004',
    name: 'Christina P.',
    email: 'christina.p@email.com',
    phone: '(713) 555-0304',
    serviceInterest: 'Dermal Fillers',
    message: 'I am interested in lip fillers and under-eye filler. I want a natural look. Can we schedule a consultation to discuss my options?',
    status: 'contacted',
    createdAt: '2026-03-20T11:00:00Z',
  },
  {
    id: 'lead-005',
    name: 'Sarah M.',
    email: 'sarah.m@email.com',
    phone: '(713) 555-0305',
    serviceInterest: 'Chemical Peel',
    message: 'I have melasma and sun damage. A friend recommended your chemical peels. What type of peel would be best for my skin concerns?',
    status: 'converted',
    createdAt: '2026-03-18T08:20:00Z',
  },
  {
    id: 'lead-006',
    name: 'Kevin D.',
    email: 'kevin.d@email.com',
    phone: '(713) 555-0306',
    serviceInterest: 'Memberships',
    message: 'I would like information about your membership program. I am interested in regular deep tissue massages and possibly facials.',
    status: 'new',
    createdAt: '2026-03-24T07:30:00Z',
  },
  {
    id: 'lead-007',
    name: 'Maria L.',
    email: 'maria.l@email.com',
    phone: '(713) 555-0307',
    serviceInterest: 'Couples Massage',
    message: 'Planning a surprise anniversary experience for my parents. Can you help me arrange a couples massage with champagne and flowers? Budget is flexible.',
    status: 'contacted',
    createdAt: '2026-03-21T13:10:00Z',
  },
  {
    id: 'lead-008',
    name: 'Patricia W.',
    email: 'patricia.w@email.com',
    phone: '(713) 555-0308',
    serviceInterest: 'Anti-Aging Facial',
    message: 'I recently turned 50 and want to start a more serious skincare regimen. What treatments do you recommend for my age group?',
    status: 'closed',
    createdAt: '2026-03-15T10:45:00Z',
  },
  {
    id: 'lead-009',
    name: 'Jennifer K.',
    email: 'jennifer.k@email.com',
    phone: '(713) 555-0309',
    serviceInterest: 'Prenatal Massage',
    message: 'I am 28 weeks pregnant and experiencing a lot of lower back pain. Is prenatal massage safe at this stage? Do I need a doctor note?',
    status: 'new',
    createdAt: '2026-03-24T10:00:00Z',
  },
];
